project:
  type: book
  output-dir: docs

book:
  favicon: "https://abs.twimg.com/emoji/v2/72x72/1f4d6.png"
  title: "Taller de investigación IV - Minería de texto"
  subtitle: "Licenciatura en sociología - UFLO"
  page-footer: "Realizado con Quarto"
  author: "Ariana Bardauil"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/ariibard/uflo-text-mining
  #repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  


  
  chapters:
    - text: "**Inicio**"
      href: index.qmd
    - part: "**Clase 1. Introducción a la Minería de Texto**"
      chapters:
        - clase1_1.qmd # Tiene los requisitos para la clase
        - clase1.qmd # La ppt
        - clase1_2.qmd # El taller practico
        
    - part: "**Clase 2. Expresiones regulares**"
      chapters:
        - clase2.qmd
        - clase2_1.qmd
        - clase2_2.qmd
        - hoja_regex.qmd

    - part: "**Clase 3. Técnicas de recolección y manipulación de datos textuales**"
      chapters:
        - clase3_1.qmd
        - clase3.qmd
        - clase3_2.qmd
        
    - part: "**Bibliografía**"
      chapters:
        - bibliografia.qmd


format:
  html:
    theme: [Pulse, estilo.scss]
    toc-title: "Índice"
    number-sections: false
  pdf:
    documentclass: scrreprt

editor: visual


  