project:
  type: book
  output-dir: docs

book:
  favicon: "https://abs.twimg.com/emoji/v2/72x72/1f4d6.png"
  title: "Taller de investigación IV - Minería de texto"
  subtitle: "Licenciatura en sociología - UFLO"
  page-footer: "© 2025 Ariana Bardauil"
  author: "Ariana Bardauil"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/ariibard/uflo-text-mining
  #repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  


  
  chapters:
    - text: "**Inicio**"
      href: index.qmd
    - part: "**Clase 1. Introducción a la Minería de Texto**"
      chapters:
        - clases/clase1_A.qmd # Tiene los requisitos para la clase
        - clases/clase1_C.qmd # La ppt
        - clases/clase1_T.qmd # El taller practico
        
    - part: "**Clase 2. Expresiones regulares**"
      chapters:
        - clases/clase2_C.qmd
        - clases/clase2_T.qmd
        - clases/clase2_TP.qmd
        - hoja_regex.qmd

    - part: "**Clase 3. Fuentes de datos textuales: APIS, Subtítulos y PDFs**"
      chapters:
        - clases/clase3_A.qmd
        - clases/clase3_C.qmd
        - clases/clase3_TP.qmd
    - part: "**Clase 4. Webscrapping**"
      chapters:
        - clases/clase4_A.qmd
        - clases/clase4_C.qmd
        - clases/clase4_TP.qmd
        - clases/clase4_Z.qmd
        
    - part: "**Clase 5. Preprocesamiento básico: tokenización, lematización, limpieza y eliminación de ruido textual**"
        
    - part: "**Referencias**"
      chapters:
        - bibliografia.qmd
        - licencia.qmd


format:
  html:
    theme: [Pulse, estilo.scss]
    toc-title: "Índice"
    number-sections: false
  pdf:
    documentclass: scrreprt

editor: visual


  