project:
  type: book
  output-dir: docs

book:
  favicon: "https://abs.twimg.com/emoji/v2/72x72/1f4d6.png"
  title: "Taller de investigación IV - Minería de texto"
  subtitle: "Licenciatura en sociología - UFLO"
  page-footer: "Realizado con Quarto"
  author: "Ariana Bardauil"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/ariibard/uflo-text-mining
  #repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  


  
  chapters:
    - index.qmd
    - part: "**Unidad 1. La minería de texto (text-mining) y la investigación social**"
      chapters:
        - clase1.qmd
        - clase2.qmd
        - hoja_regex.qmd
        - bibliografia.qmd
    - part: "**Unidad 2. Técnicas de recolección y manipulación de datos textuales**"
      chapters:
        - clase3.qmd

bibliography: references.bib

format:
  html:
    theme: [Pulse, estilo.scss]
    toc-title: "Índice"
    number-sections: false
  pdf:
    documentclass: scrreprt

editor: visual


  