---
title: "C3. Actividad entregable"
---

## Tarea: APIs y Análisis de Datos Textuales

### Objetivos

1.  Descargar información de Spotify sobre los artistas más escuchados.

2.  Consumir la API de Star Wars y descargar datos sobre los personajes.

3.  Analizar subtítulos de un video de YouTube utilizando expresiones regulares.

4.  (Opcional) Investigar y consumir otra API de tu elección.

### Instrucciones

#### Parte 1: Consumiendo datos de Spotify

1.  **Conseguir tus artistas más escuchados**:

Autentícate en la API de Spotify utilizando el paquete `{spotifyr}` y descarga información sobre tus artistas más escuchados.

Usa la función `get_my_top_artists()` para obtener esta información.

Muestra en una tabla los siguientes datos de cada artista: **nombre**, **género**, **cantidad de oyentes mensuales**.

**Tip**: No olvides configurar las credenciales de la API de Spotify.

2.  **Análisis de álbumes**:

    -   Descarga información sobre los álbumes de uno de tus artistas más escuchados utilizando la función `get_artist_albums()`.

    -   Muestra en una tabla los siguientes datos: **nombre del álbum**, **fecha de lanzamiento**, **tipo de álbum** (ej. álbum, sencillo, etc.).

#### Parte 2: Consumiendo datos de Star Wars

Utiliza la API de Star Wars (<https://www.swapi.tech/>) para obtener información sobre las peliculas, los planetas y las especies

-   Extrae los datos y muestralos en una tabla\
-   Realiza una visualización con ggplot, Highcharter o librería de visualización que te guste

#### Parte 3: Análisis de subtítulos de YouTube

1.  Selecciona un video de interés

2.  **Descargar subtítulos**

3.  Utiliza la función `get_caption()` del paquete `{youtubecaption}`

4.  Muestra los subtítulos descargados en una tabla.

5.  Realiza un análisis básico sobre los subtítulos descargados. Buscá

    ```         
     -  Palabras que se repiten con mayor frecuencia, eliminando las stopwords

     -  Frases o términos clave relacionados a X palabra utilizando expresiones regulares.
    ```

#### Parte 4: (Opcional) Inspeccionar otra API

Explora alguna de las siguientes APIs abiertas y realiza un análisis similar al de la API de Star Wars. Algunas son (puede ser otra)

-   [Pokémon API](https://pokeapi.co/) - Obtén información sobre Pokémon (por ejemplo, nombre, tipo, habilidades).

-   [The Dog API](https://thedogapi.com/) - Obtén información sobre razas de perros, imágenes, etc.

### Entrega

1.  **Sube tu código y resultados en un archivo `.Rmd` o `.R`**.

> **No te olvides de documentar el código** explicando lo que estás haciendo en cada paso.
